### PR TITLE
update MongoController.java to work with Mongo V7

### PR DESCRIPTION
**Pull request by Xiangs18**
Mostly copy from https://github.com/kbase/auth2/blob/develop/src/us/kbase/test/auth2/MongoController.java

### CODE REVIEW

**Comment by MrCreosote** [comment]
What's different from the original implementation in auth2?

**Comment by MrCreosote** [comment]
Actually, while we're at it, can you delete the directory for the shock controller?

**Comment by Xiangs18** [comment]
> Actually, while we're at it, can you delete the directory for the shock controller?

You mean us.kbase.common.test.controllers.shock folder?

**Comment by MrCreosote** [comment]
> You mean us.kbase.common.test.controllers.shock folder?
That's the one

**Comment by Xiangs18** [comment]
> What's different from the original implementation in auth2?

keep your main() and destroy()

**Comment by MrCreosote** [comment]
Not sure you mean, auth2 has main and destroy: https://github.com/kbase/auth2/blob/develop/src/us/kbase/test/auth2/MongoController.java

**Comment by MrCreosote** [comment]
Oh, you mean they're different here. Fair enough

**Comment by Xiangs18** [comment]
I mean main and destroy did not get replaced by those in auth2

**Review by MrCreosote — APPROVED** [review]

**Pull request merged**
