### PR TITLE
Opening some methods in JsonServerServlet. Removing Task Queue and AWE.

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by MrCreosote** [comment]
Looks trivial. Have you tested it with a service?

**Comment by rsutormin** [comment]
@MrCreosote: Nope, but I don't see any possible problems. And tests pass.

**Comment by MrCreosote** [comment]
The tests don't touch the jsonserverservlet as far as I know. If it were me, I'd update a server and see if it works, or update kb-sdk and run those tests. Given the triviality of the changes, however, if you want me to merge just say so, or merge yourself. We'll find out soon enough in the unlikely event the changes do break anything.

**Comment by rsutormin** [comment]
@MrCreosote: Gavin, believe me there is nothing to make bug in. :)

**Comment by rsutormin** [comment]
@MrCreosote: just checked, these changes work in njs_wrapper.

**Pull request merged**
